using DndMcpAICsharpFun.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;

// One-off migrator: copies all rows from the legacy SQLite database into Postgres,
// preserving primary keys, then resets identity sequences. Run once at cutover.
//   dotnet run --project Tools/SqliteToPostgres -- <sqlite-file> "<pg-connection-string>"

var sqlitePath = args.ElementAtOrDefault(0) ?? "data/ingestion.db";
var pgConn = args.ElementAtOrDefault(1)
    ?? "Host=localhost;Port=5432;Database=dnd;Username=dnd;Password=dnd";

AppDbContext Sqlite() => new(new DbContextOptionsBuilder<AppDbContext>()
    .UseSqlite($"Data Source={sqlitePath}").Options);
AppDbContext Pg() => new(new DbContextOptionsBuilder<AppDbContext>()
    .UseNpgsql(pgConn).Options);

Console.WriteLine($"Source SQLite: {sqlitePath}");
Console.WriteLine($"Target Postgres: {pgConn}");

await using (var pgInit = Pg())
    await pgInit.Database.MigrateAsync();

await using var src = Sqlite();
await using var dst = Pg();

var ingestion = await src.IngestionRecords.AsNoTracking().ToListAsync();
var users = await src.Users.AsNoTracking().ToListAsync();
var campaigns = await src.Campaigns.AsNoTracking().ToListAsync();
var heroes = await src.Heroes.AsNoTracking().ToListAsync();
var snapshots = await src.HeroSnapshots.AsNoTracking().ToListAsync();
var chat = await src.ChatTurns.AsNoTracking().ToListAsync();

// SQLite returns DateTimes with Kind=Unspecified; Postgres timestamptz requires UTC.
// The original values were written as UTC, so re-stamp the Kind.
static DateTime Utc(DateTime d) => DateTime.SpecifyKind(d, DateTimeKind.Utc);
static DateTime? UtcN(DateTime? d) => d.HasValue ? Utc(d.Value) : null;
foreach (var r in ingestion) { r.CreatedAt = Utc(r.CreatedAt); r.IngestedAt = UtcN(r.IngestedAt); }
foreach (var m in chat) { m.CreatedAt = Utc(m.CreatedAt); }
campaigns = campaigns.Select(c => c with { CreatedAt = Utc(c.CreatedAt) }).ToList();
heroes = heroes.Select(h => h with { CreatedAt = Utc(h.CreatedAt) }).ToList();
snapshots = snapshots.Select(s => s with { CreatedAt = Utc(s.CreatedAt) }).ToList();

dst.IngestionRecords.AddRange(ingestion);
dst.Users.AddRange(users);
dst.Campaigns.AddRange(campaigns);
dst.Heroes.AddRange(heroes);
dst.HeroSnapshots.AddRange(snapshots);
dst.ChatTurns.AddRange(chat);

// Npgsql identity columns are GENERATED BY DEFAULT — explicit ids are accepted.
await dst.SaveChangesAsync();

// Advance each identity sequence past the max copied id so new inserts don't collide.
// Table names come from a fixed local list (no user input) — EF1003 is safe to suppress here.
#pragma warning disable EF1003
foreach (var table in new[] { "IngestionRecords", "Users", "Campaigns", "Heroes", "HeroSnapshots", "ChatTurns" })
{
    await dst.Database.ExecuteSqlRawAsync(
        $"SELECT setval(pg_get_serial_sequence('\"{table}\"', 'Id'), " +
        $"GREATEST(COALESCE((SELECT MAX(\"Id\") FROM \"{table}\"), 1), 1));");
}
#pragma warning restore EF1003

// Verify row counts match.
Console.WriteLine("Row counts (source -> target):");
Console.WriteLine($"  IngestionRecords: {ingestion.Count} -> {await dst.IngestionRecords.CountAsync()}");
Console.WriteLine($"  Users:            {users.Count} -> {await dst.Users.CountAsync()}");
Console.WriteLine($"  Campaigns:        {campaigns.Count} -> {await dst.Campaigns.CountAsync()}");
Console.WriteLine($"  Heroes:           {heroes.Count} -> {await dst.Heroes.CountAsync()}");
Console.WriteLine($"  HeroSnapshots:    {snapshots.Count} -> {await dst.HeroSnapshots.CountAsync()}");
Console.WriteLine($"  ChatTurns:        {chat.Count} -> {await dst.ChatTurns.CountAsync()}");
Console.WriteLine("Migration complete.");
